### ISSUE TITLE
IE11 browser incompatible with specific JavaScript notation

### ISSUE THREAD

**Issue by flyingzebra** [masotime/json-url#4]
IE11 seems to find the '=>' sign troublesome in the following statement:

lib.compress(parsed).then(output => { ...any code... });

honestly I can't help you guys with a workaround as I'm not used to this kind of operator overloading.
Safari & Chrome on the other hand seem to cope well.

**Comment by bengoh** [comment]
@flyingzebra - that sounds more like an issue with the example provided rather than the library itself. Can you try the following:

```
lib.compress(parsed).then(function (output) {
  ... any code ...
});
```

Let me know if it works.

**Comment by flyingzebra** [comment]
Thanks for your swift reaction. I doesn't work, same problem and I can't
even squeeze an error message out of IE11. I could only make the following
statement work, unfortunately that doesn't seem to get me near the 'output'.

lib.compress(parsed).then( alert("HELLO") );

**Comment by bengoh** [comment]
Hi @flyingzebra - I've identified the issue - it's because IE11 doesn't support native Promises. You can work around this by adding this script: https://unpkg.com/es6-promise-polyfill@1.2.0/promise.js before loading JsonUrl

So for example, in HTML, you would have the following load sequence:

```
<script src="https://unpkg.com/es6-promise-polyfill@1.2.0/promise.js"></script>
<script src="https://unpkg.com/json-url@2.2.0/dist/browser/json-url.js"</script>
```

(or you can replace those with local files of course)

Let me know if this is sufficient for your use case. If not, I may consider creating a special build including a Promise polyfill in one file.

**Comment by bengoh** [comment]
To clarify, if you use the fix I have above, then the following code should work:
```
lib.compress(parsed)
.then(function(output) {
  alert(output);
});
```

**Comment by flyingzebra** [comment]
Hi @bengoh - promise.js solved the issue gracefully, thanks, this was really helpful.
Cheers

**Comment by masotime** [comment]
Great to hear @flyingzebra 👍, closing out this issue.
